apiVersion: v1
kind: ConfigMap
metadata:
  name: weddingmate-api-config
  namespace: weddingmate
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8080"
  DB_PORT: "5432"
  DB_NAME: "weddingmate"
  REDIS_PORT: "6379"
  JWT_ACCESS_TOKEN_EXPIRATION: "1800000"
  JWT_REFRESH_TOKEN_EXPIRATION: "1209600000"
