apiVersion: v1
kind: Service
metadata:
  name: weddingmate-api
  namespace: weddingmate
  labels:
    app: weddingmate-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: weddingmate-api
---
apiVersion: v1
kind: Namespace
metadata:
  name: weddingmate
